<?php

namespace DoctrineProxies\__CG__\App\Database\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PatientVisit extends \App\Database\Entities\PatientVisit implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
  'createdAt' => NULL,
  'updatedAt' => NULL,
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        unset($this->createdAt, $this->updatedAt);

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * 
     * @param string $name
     */
    public function __get($name)
    {
        if (\array_key_exists($name, self::$lazyPropertiesNames)) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', [$name]);
            return $this->$name;
        }

        trigger_error(sprintf('Undefined property: %s::$%s', __CLASS__, $name), E_USER_NOTICE);

    }

    /**
     * 
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        if (\array_key_exists($name, self::$lazyPropertiesNames)) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

            $this->$name = $value;

            return;
        }

        $this->$name = $value;
    }

    /**
     * 
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        if (\array_key_exists($name, self::$lazyPropertiesNames)) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', [$name]);

            return isset($this->$name);
        }

        return false;
    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'createdAt', 'updatedAt', 'createdBy', 'patientProcedures', 'patient', 'attendingDoctor', 'createdById', 'id', 'patientId', 'patientBP', 'patientHeight', 'patientWeight', 'remarks'];
        }

        return ['__isInitialized__', 'createdBy', 'patientProcedures', 'patient', 'attendingDoctor', 'createdById', 'id', 'patientId', 'patientBP', 'patientHeight', 'patientWeight', 'remarks'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PatientVisit $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

            unset($this->createdAt, $this->updatedAt);
        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getAttendingDoctor(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttendingDoctor', []);

        return parent::getAttendingDoctor();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): \DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedById(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedById', []);

        return parent::getCreatedById();
    }

    /**
     * {@inheritDoc}
     */
    public function getPatientId(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPatientId', []);

        return parent::getPatientId();
    }

    /**
     * {@inheritDoc}
     */
    public function getPatientBP(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPatientBP', []);

        return parent::getPatientBP();
    }

    /**
     * {@inheritDoc}
     */
    public function getPatientHeight(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPatientHeight', []);

        return parent::getPatientHeight();
    }

    /**
     * {@inheritDoc}
     */
    public function getPatientWeight(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPatientWeight', []);

        return parent::getPatientWeight();
    }

    /**
     * {@inheritDoc}
     */
    public function getRemarks(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemarks', []);

        return parent::getRemarks();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): \DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttendingDoctor(?string $attendingDoctor): \App\Database\Entities\PatientVisit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttendingDoctor', [$attendingDoctor]);

        return parent::setAttendingDoctor($attendingDoctor);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeInterface $createdAt): \App\Database\Entities\PatientVisit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy(\App\Database\Entities\UserGuest $user): \App\Database\Entities\PatientVisit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', [$user]);

        return parent::setCreatedBy($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTimeInterface $updatedAt): \App\Database\Entities\PatientVisit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function setPatient(\App\Database\Entities\Patient $patient): \App\Database\Entities\PatientVisit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPatient', [$patient]);

        return parent::setPatient($patient);
    }

    /**
     * {@inheritDoc}
     */
    public function setPatientBP(string $patientBP): \App\Database\Entities\PatientVisit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPatientBP', [$patientBP]);

        return parent::setPatientBP($patientBP);
    }

    /**
     * {@inheritDoc}
     */
    public function setPatientHeight(string $patientHeight): \App\Database\Entities\PatientVisit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPatientHeight', [$patientHeight]);

        return parent::setPatientHeight($patientHeight);
    }

    /**
     * {@inheritDoc}
     */
    public function setPatientWeight(string $patientWeight): \App\Database\Entities\PatientVisit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPatientWeight', [$patientWeight]);

        return parent::setPatientWeight($patientWeight);
    }

    /**
     * {@inheritDoc}
     */
    public function setRemarks(string $remarks): \App\Database\Entities\PatientVisit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRemarks', [$remarks]);

        return parent::setRemarks($remarks);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAtAsString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAtAsString', []);

        return parent::getCreatedAtAsString();
    }

    /**
     * {@inheritDoc}
     */
    public function getRules(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRules', []);

        return parent::getRules();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAtAsString(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAtAsString', []);

        return parent::getUpdatedAtAsString();
    }

    /**
     * {@inheritDoc}
     */
    public function getValidationFailedException(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidationFailedException', []);

        return parent::getValidationFailedException();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function __call(string $method, array $parameters)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__call', [$method, $parameters]);

        return parent::__call($method, $parameters);
    }

    /**
     * {@inheritDoc}
     */
    public function fill(array $data): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'fill', [$data]);

        parent::fill($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getFillableProperties(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFillableProperties', []);

        return parent::getFillableProperties();
    }

    /**
     * {@inheritDoc}
     */
    public function getValidatableProperties(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidatableProperties', []);

        return parent::getValidatableProperties();
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

    /**
     * {@inheritDoc}
     */
    public function toJson(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toJson', []);

        return parent::toJson();
    }

    /**
     * {@inheritDoc}
     */
    public function toXml(string $rootNode = NULL): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toXml', [$rootNode]);

        return parent::toXml($rootNode);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

}
